import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "@/app/ui/globals.css";
import styles from "@/app/ui/layout/layout.module.scss";
import Header from "@/app/ui/layout/header/header";
import Footer from "@/app/ui/layout/footer/footer";
const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // MOCK
  const title = "";
  return (
    <html lang="en">
      {/* <BackgroundImage
       Tag="div"
       className={styles.bg}
       fluid={data.bg.childImageSharp.fluid}
       backgroundColor={`#19182F`}
      > */}
      <body className={styles.layout + " " + raleway.className}>
        <Header siteTitle={"title"} className={styles.header} />
        <main className={styles.content}>{children}</main>
        <Footer className={styles.footer} title={title} />
        {/* </BackgroundImage> */}
      </body>
    </html>
  );
}
